---
  - hosts: centos
    become: true
    roles:
      - clean-tetration-sensor-centos
      - install-tetration-sensor-sh-centos

  - hosts: ubuntu
    become: true
    roles:
      - clean-tetration-sensor-ubuntu
      - install-tetration-sensor-sh-ubuntu

  - hosts: win
    roles:
      - clean-tetration-sensor-win
      - install-tetration-sensor-ps-win
      